Repository LiveSplit/asr, pull requests merged in 2023-05, with the labels that each got.

#24 Add a macro for defining a panic handler
  Cargo.toml
  src/lib.rs
  src/panic.rs
  src/runtime/mod.rs
  src/runtime/sys.rs
Labels: enhancement

#25 Add support for asynchronous code
  .github/workflows/build.yml
  README.md
  src/future.rs
  src/lib.rs
Labels: enhancement

#27 Improve address handling
  src/gba.rs
  src/lib.rs
  src/primitives.rs
  src/primitives/address.rs
  src/primitives/endian.rs
  src/primitives/mod.rs
  src/runtime/memory_range.rs
  src/runtime/mod.rs
  src/runtime/process.rs
  src/runtime/sys.rs
  src/signature.rs
Labels: enhancement

#28 Fix the future support a little
  src/future.rs
Labels: enhancement

#29 Fix Doc Tests
  .github/workflows/build.yml
  src/future.rs
  src/lib.rs
  src/panic.rs
Labels: bug, documentation, enhancement

#30 Take `Into<Address>` as argument
  src/emulator/gba.rs
  src/emulator/mod.rs
  src/future.rs
  src/lib.rs
  src/runtime/memory_range.rs
  src/runtime/process.rs
  src/signature.rs
  src/string.rs
  src/watcher.rs
Labels: enhancement

#31 Implement File Format Parsing
  src/emulator/genesis/mod.rs
  src/emulator/genesis/retroarch.rs
  src/file_format/elf.rs
  src/file_format/mod.rs
  src/file_format/pe.rs
  src/lib.rs
Labels: enhancement

#32 Support functions retrying `Result` in `retry`
  src/future.rs
Labels: enhancement

#33 Added support for PS1 emulators
  Cargo.toml
  src/emulator/genesis/mod.rs
  src/emulator/mod.rs
  src/emulator/ps1/duckstation.rs
  src/emulator/ps1/epsxe.rs
  src/emulator/ps1/mod.rs
  src/emulator/ps1/pcsx_redux.rs
  src/emulator/ps1/psxfin.rs
  src/emulator/ps1/retroarch.rs
  src/emulator/ps1/xebra.rs
Labels: enhancement

#34 Fix missing `signature` features for emulators
  Cargo.toml
Labels: bug, enhancement

#37 Allow accessing the path of a process
  Cargo.toml
  src/lib.rs
  src/runtime/process.rs
  src/runtime/sys.rs
Labels: enhancement
