Repository LiveSplit/asr, pull requests merged in 2023-10, with the labels that each got.

#66 Added the ability to iterate over exported symbols in a given pe module
  src/file_format/pe.rs
Labels: enhancement

#65 [BUGFIX] Added new sigscan for DuckStation (PS1 emu)
  src/emulator/ps1/duckstation.rs
Labels: bug, enhancement

#72 Add settings maps and values
  asr-derive/src/lib.rs
  asr-derive/src/unity.rs
  src/emulator/gba/retroarch.rs
  src/future/mod.rs
  src/game_engine/unity/il2cpp.rs
  src/game_engine/unity/mono.rs
  src/game_engine/unity/scene.rs
  src/runtime/mod.rs
  src/runtime/settings/gui.rs
  src/runtime/settings/map.rs
  src/runtime/settings/mod.rs
  src/runtime/settings/value.rs
  src/runtime/sys.rs
Labels: enhancement

#74 Improve the documentation for the settings
  asr-derive/src/lib.rs
  src/runtime/settings/mod.rs
Labels: documentation
